//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecm.DbLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public double Value { get; set; }
        public int EnergyTypeId { get; set; }
        public int PeriodicityId { get; set; }
        public int UserId { get; set; }
        public string Note { get; set; }
    
        public virtual EnergyType EnergyType { get; set; }
        public virtual Periodicity Periodicity { get; set; }
        public virtual User User { get; set; }
    }
}
